#!/bin/sh

#
# Build an OpenVPN plugin module on *nix.  The argument should
# be the base name of the C source file (without the .c).
#

# This directory is where we will look for openvpn-plugin.h
INCLUDE="-I../.."

CC_FLAGS="-O2 -Wall -g"

gcc $CC_FLAGS -fPIC -c $INCLUDE $1.c && \
gcc $CC_FLAGS -fPIC -shared -Wl,-soname,$1.so -o $1.so $1.o -lc
