#!/bin/sh

# copy the installer to the $INSTALLER_DEST directory.

# load version.nsi definitions
. autodefs/defs.sh

if [ -n "$INSTALLER_DEST" ] ; then
    cd install-win32
    ls openvpn*.exe 2>/dev/null || exit 1
    exe=install-win32/`ls -t openvpn*.exe | head -n 1`
    cd ..
    echo cp $exe "$INSTALLER_DEST"
    cp $exe "$INSTALLER_DEST"
fi
