#!/bin/sh

# get version.nsi definitions
. autodefs/defs.sh

# Get OpenSSL binaries
if [ -d "$OPENSSL_DIR" ] ; then
    mkdir -p $GENOUT/lib &>/dev/null    
    mkdir -p $GENOUT/bin &>/dev/null    
    for f in libeay32.dll libssl32.dll openssl.exe ; do
	cp $OPENSSL_DIR/$f $GENOUT/lib
	strip $GENOUT/lib/$f
    done
    mv $GENOUT/lib/openssl.exe $GENOUT/bin
else
    echo OpenSSL DIR $OPENSSL_DIR NOT FOUND
fi
