#!/bin/sh

# get version.nsi definitions
. autodefs/defs.sh

# Get PKCS11-helper libraries
if [ -d "$PKCS11_HELPER_DIR" ] ; then
    mkdir -p $GENOUT/lib &>/dev/null    
    for f in libpkcs11-helper-1.dll ; do
	cp $PKCS11_HELPER_DIR/usr/local/bin/$f $GENOUT/lib
        if [ -z "$NO_STRIP" ]; then
	    strip $GENOUT/lib/$f
	fi
    done
else
    echo PKCS11-helper DIR $PKCS11_HELPER_DIR NOT FOUND
fi
