#!/bin/sh

# get version.nsi definitions
. autodefs/defs.sh

if gcc --version &>/dev/null && [ -d "$OPENSSL_DIR" ] && [ -d "$LZO_DIR" ] && [ -d "$PKCS11_HELPER_DIR" ]; then
    # build OpenVPN binary
    [ "$CLEAN" = "yes" ] && make -f makefile.w32 clean
    make -f makefile.w32 -j $MAKE_JOBS

    # copy OpenVPN executable to GENOUT/bin
    mkdir -p $GENOUT/bin &>/dev/null
    cp $PRODUCT_UNIX_NAME.exe $GENOUT/bin
    strip $GENOUT/bin/$PRODUCT_UNIX_NAME.exe
else
    echo DID NOT BUILD openvpn.exe because one or more of gcc, OPENSSL_DIR, LZO_DIR, or PKCS11_HELPER_DIR directories were missing
fi
