#!/bin/sh

# Build the x86 and x64 versions of the TAP driver
# Requires the Windows DDK

DDKVER=3790

cd tap-win32
t=`pwd`
cd ..

for mode in "fre WNET" "fre AMD64 WNET"; do
  echo '**********' build TAP $mode
  cmd //c "C:\\WINDDK\\$DDKVER\\bin\\setenv.bat C:\\WINDDK\\$DDKVER $mode && cd `perl install-win32/dosname.pl $t` && build -cef"
done
