#!/bin/sh

# Build the x86 and x64 versions of the tapinstall tool
# Requires the Windows DDK.
# TISRC should be set to directory containing
# tapinstall source code.

# get version.nsi definitions
. autodefs/nsidefs.sh

if [ -z "$DRVBINSRC" ] ; then
    rm -rf tapinstall
    cp -a "$TISRC" tapinstall

    cd tapinstall
    t=`pwd`
    cd ..

    # Add "fre AMD64 WNET" to below line to also build X64 version
    for mode in "fre WNET" ; do
	echo '**********' build TAPINSTALL $mode
	cmd //c "C:\\WINDDK\\$DDKVER\\bin\\setenv.bat C:\\WINDDK\\$DDKVER $mode && cd `perl install-win32/dosname.pl $t` && build -cef"
    done
fi
