#!/bin/sh

# Assemble binaries into bin

# get version.nsi definitions
. autodefs/nsidefs.sh

rm -rf bin
mkdir bin

# Get OpenVPN executable
cp openvpn.exe bin
strip bin/openvpn.exe

# Get OpenVPN service
cp service-win32/openvpnserv.exe bin
strip bin/openvpnserv.exe

# Get OpenSSL binaries
for f in libeay32.dll libssl32.dll openssl.exe ; do
  cp ../openssl-${OPENSSL_VERSION}/$f bin
  strip bin/$f
done

# Get TAP drivers
cp -a tap-win32/dist bin/driver

# Get tapinstall
mkdir bin/tapinstall
mkdir bin/tapinstall/i386
mkdir bin/tapinstall/amd64
cp tapinstall/objfre_wnet_x86/i386/tapinstall.exe bin/tapinstall/i386
cp tapinstall/objfre_wnet_amd64/amd64/tapinstall.exe bin/tapinstall/amd64
