#!/bin/sh

# Sign the x86 and x64 versions of the TAP driver

# SIGNCODE should point to directory with signcode.exe and keys
# INF2CAT should point to the MS inf2cat distribution

c=`pwd`

# load version.nsi definitions
. autodefs/nsidefs.sh

if [ -z "$DRVBINSRC" ] ; then
    # copy driver files into tap-win32/dist
    cd tap-win32
    rm -rf dist
    mkdir dist
    cd dist
    mkdir i386
    mkdir amd64
    cd i386
    x86=`pwd`
    cd ../amd64
    x64=`pwd`
    cd ../..
    cp i386/OemWin2k.inf $x86
    cp i386/*.sys $x86
    cp amd64/OemWin2k.inf $x64
    cp amd64/*.sys $x64
    cd $c

    if [ -n "$SIGNCODE" ] && [ -n "$INF2CAT" ] ; then
	cd "$INF2CAT"

	echo '******************' BUILD .cat FILE for x86
	cmd //c "inf2cat /driver:`perl $c/install-win32/dosname.pl $x86` /os:2000,XP_X86,Server2003_X86,Vista_X86"

	echo '******************' BUILD .cat FILE for x64
	cmd //c "inf2cat /driver:`perl $c/install-win32/dosname.pl $x64` /os:XP_X64,Server2003_X64,Vista_X64"

	cd $c
	cd "$SIGNCODE"

	TS="http://timestamp.verisign.com/scripts/timstamp.dll"
	echo '******************' SIGNCODE .cat FILE for x86
	./signcode -spc mycredentials.spc -v myprivatekey.pvk -a sha1 -n "OpenVPN TAP-Win32 Driver" -t $TS `perl $c/install-win32/dosname.pl $x86/tap.cat`
	echo '******************' SIGNCODE .cat FILE for x64
	./signcode -spc mycredentials.spc -v myprivatekey.pvk -a sha1 -n "OpenVPN TAP-Win64 Driver" -t $TS `perl $c/install-win32/dosname.pl $x64/tap.cat`
    else
	out="TAP driver catalog file is undefined";
	echo "$out" >$x86/tap.cat
	echo "$out" >$x64/tap.cat
    fi
fi
