#!/bin/sh

# Sign the installer.

c=`pwd`

# load version.nsi definitions
. autodefs/defs.sh

if [ -d "$SIGNTOOL" ]; then
    cd install-win32
    ls *.exe 2>/dev/null || exit 1
    export TARGET_EXE=$(pwd)/$(ls -t *.exe | head -n 1)
    cd $c
    $SIGNTOOL/signexe
fi
