#!/bin/bash
PROGDIR=`dirname $0`
unset LD_LIBRARY_PATH
valgrind --tool=memcheck --error-limit=no --suppressions=$PROGDIR/debug/valgrind-suppress --gen-suppressions=all --leak-check=full --show-reachable=yes --num-callers=32 $PROGDIR/openvpn "$@"
