#!/bin/sh

# Let's have a fresh start.  Remove all files
# which are not source files.
#
# Run this script, then:
#        touch *
#        [apply any patches here]
#        autoreconf -i -v
#        ./configure
#        make
#        make install

rm -f *.o openvpn config.cache configure Makefile Makefile.in stamp-h* config.guess config.sub depcomp missing mkinstalldirs config.log config.status config.h config.h.in aclocal.m4 openvpn.spec install-sh

rm -rf autom4te*.cache .deps
