#!/bin/sh

# This is the master OpenVPN build script for Windows.
# See top-devel definitions in install-win32/version.nsi
#
# Example usage:
#
# make without signing:
#  SIGNCODE="null" ./domake-win
#
# write installer to desktop
#  INSTALLER_DEST="/c/Documents and Settings/James/Desktop" ./domake-win

install-win32/winconfig
install-win32/makeopenvpn
install-win32/maketapinstall
install-win32/maketap
install-win32/signtap
install-win32/makebin
install-win32/buildinstaller
install-win32/signinstaller
install-win32/copyinstaller
