#!/bin/sh

# make without signing:
#  SIGNCODE="null" ./domake-win

install-win32/winconfig
install-win32/makeopenvpn
install-win32/maketapinstall
install-win32/maketap
install-win32/signtap
install-win32/makebin
install-win32/buildinstaller
install-win32/signinstaller
install-win32/copyinstaller
