#!/bin/sh

#
# Similar to build-key, but protect the private key
# with a password.
#

if test $# -ne 1; then
        echo "usage: build-key-pass <name>";
        exit 1
fi

if test $KEY_DIR; then
	cd $KEY_DIR && \
	openssl req -days 3650 -new -keyout $1.key -out $1.csr -config $KEY_CONFIG && \
	openssl ca -days 3650 -out $1.crt -in $1.csr -config $KEY_CONFIG && \
	chmod 0600 $1.key
else
	echo you must define KEY_DIR
fi
