#!/bin/sh

#
# Initialize the $KEY_DIR directory.
# Note that this script does a
# rm -rf on $KEY_DIR so be careful!
#

d=$KEY_DIR

if test $d; then
	rm -rf $d
	mkdir $d && \
	chmod go-rwx $d && \
	touch $d/index.txt && \
	echo 01 >$d/serial
else
	echo you must define KEY_DIR
fi
