name: Deploy Doxygen documentation to Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch:
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'openvpn' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: openvpn

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential doxygen graphviz \
            liblzo2-dev libpam0g-dev liblz4-dev libcap-ng-dev libnl-genl-3-dev linux-libc-dev man2html libcmocka-dev python3-docutils libtool automake autoconf libssl-dev

      - name: Build Doxygen documentation
        id: build
        run: |
          cd openvpn
          autoreconf -f -i
          cd ..
          mkdir doxygen
          cd doxygen
          ../openvpn/configure
          make doxygen
          touch doc/doxygen/html/.nojekyll
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: doxygen/doc/doxygen/html/

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
