name: Deploy Doxygen documentation to Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch:
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'openvpn' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: openvpn

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential doxygen graphviz \
            liblzo2-dev libpam0g-dev liblz4-dev libcap-ng-dev libnl-genl-3-dev linux-libc-dev man2html libcmocka-dev python3-docutils libtool automake autoconf libssl-dev

      - name: Build Doxygen documentation
        id: build
        run: |
          cd openvpn
          autoreconf -f -i
          cd ..
          mkdir doxygen
          cd doxygen
          ../openvpn/configure
          make doxygen
          touch doc/doxygen/html/.nojekyll
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: doxygen/doc/doxygen/html/

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
